#!/bin/bash

# ============================================
# STEP 04: NEXTFLOW TEST RUN
# PURPOSE:
#   Validate the nf-core/cutandrun installation with the
#   bundled test profile before running the full dataset.
# OUTPUT:
#   Test output directory generated by Nextflow.
# ============================================

# NXF_VER=24.10.0 nextflow run nf-core/cutandrun \
#     -profile test,docker \
#     --outdir /mnt/nas-safu03/analysis/vazyme_chip_0525/nextflow_test \
#     -r 3.2.1
